spring:
  datasource:
    url: url to db
    username: username
    password: password

upload:
  name:
    cartoons: cartoons name
    movies: movies name
    serialMovies: serialMovies name
    music: music name
    videos: videos name
  location:
    cartoons: cartoons location
    movies: movies location
    serialMovies: serialMovies location
    music: music location
    videos: videos location

## http://www.omdbapi.com/
omdbapi:
  endpoint: http://www.omdbapi.com/
  name:
    title: t
    year: y
    id: i
    apikey: apikeyName
  value:
    apikey: apikeyValue

## https://developers.themoviedb.org/3/getting-started/introduction
tmdbapi:
  endpoint: https://api.themoviedb.org/3/search/movie
  name:
    title: query
    year: primary_release_year
    apikey: api_key
  value:
    apikey: apikeyValue