import React, {useState} from 'react';
import Card from "../Card/Card";
import "./Body.css";

const body = () => {
    const [movieList, setMovieList] = useState([
        {
            "id": 100000,
            "tmdbId": "9487",
            "title": "A Bug's Life",
            "releaseDate": "1998-11-25",
            "posterPath": "/kHgWI1AbYnYPZrUl5DCwzq9tyB2.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.94,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100001,
            "tmdbId": "17979",
            "title": "A Christmas Carol",
            "releaseDate": "2009-11-04",
            "posterPath": "/goHDZUnqZJ7FN4h48Qh6MzJNExl.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.78,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100002,
            "tmdbId": "77459",
            "title": "A Monster in Paris",
            "releaseDate": "2011-10-12",
            "posterPath": "/jerM6xBeRfIr2rLg2pICmduzoyf.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.51,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100003,
            "tmdbId": "431580",
            "title": "Abominable",
            "releaseDate": "2019-09-19",
            "posterPath": "/20djTLqppfBx5WYA67Y300S6aPD.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.01,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100004,
            "tmdbId": "812",
            "title": "Aladdin",
            "releaseDate": "1992-11-25",
            "posterPath": "/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5,
            "location": "\\\\DELL_E6540\\k_cartoons\\Aladdin",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100005,
            "tmdbId": "15969",
            "title": "The Return of Jafar",
            "releaseDate": "1994-12-15",
            "posterPath": "/7SC793qtORB6YL4mu0F5o3hfjDQ.jpg",
            "type": "movie",
            "resolution": "VGA",
            "size": 0.67,
            "location": "\\\\DELL_E6540\\k_cartoons\\Aladdin",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100006,
            "tmdbId": "11238",
            "title": "Aladdin and the King of Thieves",
            "releaseDate": "1996-05-20",
            "posterPath": "/kTH7qEyvdDYMoQraQZm3LFKCge3.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.91,
            "location": "\\\\DELL_E6540\\k_cartoons\\Aladdin",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100007,
            "tmdbId": "420817",
            "title": "Aladdin",
            "releaseDate": "2019-05-22",
            "posterPath": "/ykUEbfpkf8d0w49pHh0AD2KrT52.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.17,
            "location": "\\\\DELL_E6540\\k_cartoons\\Aladdin",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100008,
            "tmdbId": "12092",
            "title": "Alice in Wonderland",
            "releaseDate": "1951-07-28",
            "posterPath": "/1cbF3s99hCQcFdWG8hrGhKSBles.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100009,
            "tmdbId": "9444",
            "title": "Anastasia",
            "releaseDate": "1997-11-20",
            "posterPath": "/lQwTsdtJwxanuJPdS4Ltx5ngUBJ.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.82,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100010,
            "tmdbId": "10865",
            "title": "Atlantis: The Lost Empire",
            "releaseDate": "2001-06-02",
            "posterPath": "/8fUEFPUTF7kBMuKPiSQHxPvd8EZ.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.37,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100011,
            "tmdbId": "3170",
            "title": "Bambi",
            "releaseDate": "1942-08-14",
            "posterPath": "/wV9e2y4myJ4KMFsyFfWYcUOawyK.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.8,
            "location": "\\\\DELL_E6540\\k_cartoons\\Bambi",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100012,
            "tmdbId": "13205",
            "title": "Bambi II",
            "releaseDate": "2006-01-26",
            "posterPath": "/wIVLCnwYynKIiAheJoEQtC8gTjq.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.9,
            "location": "\\\\DELL_E6540\\k_cartoons\\Bambi",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100013,
            "tmdbId": "10020",
            "title": "Beauty and the Beast",
            "releaseDate": "1991-11-13",
            "posterPath": "/7oCAPOphDKpIaxTrnukmDrZ8XKD.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 12.85,
            "location": "\\\\DELL_E6540\\k_cartoons\\Beauty and Beast",
            "description": "Ext",
            "frameRate": 24
        },
        {
            "id": 100014,
            "tmdbId": "13313",
            "title": "Beauty and the Beast: The Enchanted Christmas",
            "releaseDate": "1997-11-11",
            "posterPath": "/qxtpbcbf6KEIHzLetWZOVGJT2lv.jpg",
            "type": "movie",
            "resolution": "VGA",
            "size": 0.68,
            "location": "\\\\DELL_E6540\\k_cartoons\\Beauty and Beast",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100015,
            "tmdbId": "2310",
            "title": "Beowulf",
            "releaseDate": "2007-11-05",
            "posterPath": "/cq3FPhKCeCGI2XIbAgaUkiMbLsY.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.05,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100016,
            "tmdbId": "177572",
            "title": "Big Hero 6",
            "releaseDate": "2014-10-24",
            "posterPath": "/2mxS4wUimwlLmI1xp6QW6NSU361.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 7.92,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100017,
            "tmdbId": "13053",
            "title": "Bolt",
            "releaseDate": "2008-11-21",
            "posterPath": "/z9VHoUcZ1GiH3f3qYz7Me7Zc1Fd.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.08,
            "location": "\\\\DELL_E6540\\k_cartoons\\Bolt",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100018,
            "tmdbId": "16604",
            "title": "Super Rhino",
            "releaseDate": "2009-03-21",
            "posterPath": "/aOoq1GriFCdI9FRWDOgihKn6rlX.jpg",
            "type": "movie",
            "resolution": "VGA",
            "size": 0.09,
            "location": "\\\\DELL_E6540\\k_cartoons\\Bolt\\Shorts",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100019,
            "tmdbId": "62177",
            "title": "Brave",
            "releaseDate": "2012-06-21",
            "posterPath": "/L6qqU6Q3k4MmPojncNbT43FSTL.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.17,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100020,
            "tmdbId": "920",
            "title": "Cars",
            "releaseDate": "2006-06-08",
            "posterPath": "/qa6HCwP4Z15l3hpsASz3auugEW6.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.6,
            "location": "\\\\DELL_E6540\\k_cartoons\\Cars",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100021,
            "tmdbId": "49013",
            "title": "Cars 2",
            "releaseDate": "2011-06-11",
            "posterPath": "/okIz1HyxeVOMzYwwHUjH2pHi74I.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.2,
            "location": "\\\\DELL_E6540\\k_cartoons\\Cars",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100022,
            "tmdbId": "10515",
            "title": "Castle in the Sky",
            "releaseDate": "1986-08-02",
            "posterPath": "/npOnzAbLh6VOIu3naU5QaEcTepo.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 7.53,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100023,
            "tmdbId": "9982",
            "title": "Chicken Little",
            "releaseDate": "2005-11-04",
            "posterPath": "/1wg65q3daTE8rGfaUhBxLdXk6NL.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.28,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100024,
            "tmdbId": "420814",
            "title": "Christopher Robin",
            "releaseDate": "2018-08-02",
            "posterPath": "/i6Ytex4d3CdfIKJFxB5v5vh24vb.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.81,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100025,
            "tmdbId": "11224",
            "title": "Cinderella",
            "releaseDate": "1950-02-22",
            "posterPath": "/4nssBcQUBadCTBjrAkX46mVEKts.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100026,
            "tmdbId": "150689",
            "title": "Cinderella",
            "releaseDate": "2015-03-12",
            "posterPath": "/ryKwNlAfDXu0do6SX9h4G9Si1kG.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 13.53,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100027,
            "tmdbId": "22794",
            "title": "Cloudy with a Chance of Meatballs",
            "releaseDate": "2009-09-17",
            "posterPath": "/qhOhIKf7QEyQ5dMrRUqs5eTX1Oq.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.25,
            "location": "\\\\DELL_E6540\\k_cartoons\\Cloudy with a Chance of Meatballs",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100028,
            "tmdbId": "109451",
            "title": "Cloudy with a Chance of Meatballs 2",
            "releaseDate": "2013-09-26",
            "posterPath": "/tT2DN1tWk1zpCxqvaaNY8yP8Awn.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.69,
            "location": "\\\\DELL_E6540\\k_cartoons\\Cloudy with a Chance of Meatballs",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100029,
            "tmdbId": "354912",
            "title": "Coco",
            "releaseDate": "2017-10-27",
            "posterPath": "/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.81,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100030,
            "tmdbId": "3933",
            "title": "Corpse Bride",
            "releaseDate": "2005-09-12",
            "posterPath": "/isb2Qow76GpqYmsSyfdMfsYAjts.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.9,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100031,
            "tmdbId": "20352",
            "title": "Despicable Me",
            "releaseDate": "2010-07-08",
            "posterPath": "/wqtH95Ri9Au2euC4p86lLoFCJQk.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.36,
            "location": "\\\\DELL_E6540\\k_cartoons\\Despicable Me",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100032,
            "tmdbId": "93456",
            "title": "Despicable Me 2",
            "releaseDate": "2013-06-25",
            "posterPath": "/5Fh4NdoEnCjCK9wLjdJ9DJNFl2b.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.9,
            "location": "\\\\DELL_E6540\\k_cartoons\\Despicable Me",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100033,
            "tmdbId": "324852",
            "title": "Despicable Me 3",
            "releaseDate": "2017-06-15",
            "posterPath": "/6t3YWl7hrr88lCEFlGVqW5yV99R.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.79,
            "location": "\\\\DELL_E6540\\k_cartoons\\Despicable Me",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100034,
            "tmdbId": "211672",
            "title": "Minions",
            "releaseDate": "2015-06-17",
            "posterPath": "/vlOgaxUiMOA8sPDG9n3VhQabnEi.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 12.09,
            "location": "\\\\DELL_E6540\\k_cartoons\\Despicable Me",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100035,
            "tmdbId": "10567",
            "title": "Dinosaur",
            "releaseDate": "2000-05-19",
            "posterPath": "/rSje3FS7ycJSglowlngjsvDt7vO.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.26,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100036,
            "tmdbId": "11360",
            "title": "Dumbo",
            "releaseDate": "1941-10-22",
            "posterPath": "/hKDdllslMtsU9JixAv5HR9biXlp.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.71,
            "location": "\\\\DELL_E6540\\k_cartoons\\Dumbo",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100037,
            "tmdbId": "329996",
            "title": "Dumbo",
            "releaseDate": "2019-03-27",
            "posterPath": "/deTOAcMWuHTjOUPQphwcPFFfTQz.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9,
            "location": "\\\\DELL_E6540\\k_cartoons\\Dumbo",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100038,
            "tmdbId": "116711",
            "title": "Epic",
            "releaseDate": "2013-05-15",
            "posterPath": "/rdi6MYgAhLlgomEERtmYtrH8ItY.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.16,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100039,
            "tmdbId": "364689",
            "title": "Ferdinand",
            "releaseDate": "2017-12-09",
            "posterPath": "/rMm94JsRfcOPiPVsTRcBiiVBOhz.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.54,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100040,
            "tmdbId": "109445",
            "title": "Frozen",
            "releaseDate": "2013-11-20",
            "posterPath": "/AmFIGmQRkmAoHhBtlaHkO6RoPOq.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 8.24,
            "location": "\\\\DELL_E6540\\k_cartoons\\Frozen",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100041,
            "tmdbId": "330457",
            "title": "Frozen II",
            "releaseDate": "2019-11-20",
            "posterPath": "/mINJaa34MtknCYl5AjtNJzWj8cD.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.25,
            "location": "\\\\DELL_E6540\\k_cartoons\\Frozen",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100042,
            "tmdbId": "8920",
            "title": "Garfield",
            "releaseDate": "2004-06-10",
            "posterPath": "/5hKlKh62yIR03XHZxwFs3EaIFfD.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.36,
            "location": "\\\\DELL_E6540\\k_cartoons\\Garfield",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100043,
            "tmdbId": "9513",
            "title": "Garfield: A Tail of Two Kitties",
            "releaseDate": "2006-06-15",
            "posterPath": "/osfMaHucgLtHtsMa6TQLTooE3G7.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.28,
            "location": "\\\\DELL_E6540\\k_cartoons\\Garfield",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100044,
            "tmdbId": "11970",
            "title": "Hercules",
            "releaseDate": "1997-06-20",
            "posterPath": "/16JPL3c6ET7ibfO35WjjWxCaVmj.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.07,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100045,
            "tmdbId": "228161",
            "title": "Home",
            "releaseDate": "2015-03-18",
            "posterPath": "/usFenYnk6mr8C62dB1MoAfSWMGR.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.62,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100046,
            "tmdbId": "13700",
            "title": "Home on the Range",
            "releaseDate": "2004-04-02",
            "posterPath": "/9xIIo4FMquy5SRqn8hppyr2QadR.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.23,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100047,
            "tmdbId": "12222",
            "title": "Horton Hears a Who!",
            "releaseDate": "2008-03-03",
            "posterPath": "/6k47Z3A5zI2rxubTMwiLyIqQLLr.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.01,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100048,
            "tmdbId": "76492",
            "title": "Hotel Transylvania",
            "releaseDate": "2012-09-20",
            "posterPath": "/eJGvzGrsfe2sqTUPv5IwLWXjVuR.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.1,
            "location": "\\\\DELL_E6540\\k_cartoons\\Hotel Transylvania",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100049,
            "tmdbId": "159824",
            "title": "Hotel Transylvania 2",
            "releaseDate": "2015-09-21",
            "posterPath": "/kKFgwQnR5q08UFsAvtoYyTIiHyj.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.13,
            "location": "\\\\DELL_E6540\\k_cartoons\\Hotel Transylvania",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100050,
            "tmdbId": "400155",
            "title": "Hotel Transylvania 3: Summer Vacation",
            "releaseDate": "2018-06-28",
            "posterPath": "/o7RY5zNHdH2heGS1hET2Rt6hZOe.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.02,
            "location": "\\\\DELL_E6540\\k_cartoons\\Hotel Transylvania",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100051,
            "tmdbId": "10191",
            "title": "How to Train Your Dragon",
            "releaseDate": "2010-03-10",
            "posterPath": "/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.79,
            "location": "\\\\DELL_E6540\\k_cartoons\\How to Train Your Dragon",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100052,
            "tmdbId": "82702",
            "title": "How to Train Your Dragon 2",
            "releaseDate": "2014-06-09",
            "posterPath": "/d13Uj86LdbDLrfDoHR5aDOFYyJC.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.64,
            "location": "\\\\DELL_E6540\\k_cartoons\\How to Train Your Dragon",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100053,
            "tmdbId": "166428",
            "title": "How to Train Your Dragon: The Hidden World",
            "releaseDate": "2019-01-03",
            "posterPath": "/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.85,
            "location": "\\\\DELL_E6540\\k_cartoons\\How to Train Your Dragon",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100054,
            "tmdbId": "4935",
            "title": "Howl's Moving Castle",
            "releaseDate": "2004-11-19",
            "posterPath": "/TkTPELv4kC3u1lkloush8skOjE.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.84,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100055,
            "tmdbId": "425",
            "title": "Ice Age",
            "releaseDate": "2002-03-10",
            "posterPath": "/gLhHHZUzeseRXShoDyC4VqLgsNv.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.31,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ice Age",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100056,
            "tmdbId": "950",
            "title": "Ice Age: The Meltdown",
            "releaseDate": "2006-03-29",
            "posterPath": "/hzJzd0OFRHjSykLuSmDG8ssPJAn.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.61,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ice Age",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100057,
            "tmdbId": "8355",
            "title": "Ice Age: Dawn of the Dinosaurs",
            "releaseDate": "2009-06-29",
            "posterPath": "/cXOLaxcNjNAYmEx1trZxOTKhK3Q.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.13,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ice Age",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100058,
            "tmdbId": "57800",
            "title": "Ice Age: Continental Drift",
            "releaseDate": "2012-06-26",
            "posterPath": "/6NSFKyOz7ppsd0KY6g4HInIZ53P.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.26,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ice Age",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100059,
            "tmdbId": "278154",
            "title": "Ice Age: Collision Course",
            "releaseDate": "2016-06-23",
            "posterPath": "/xczYhncwMnuX98AshyZHgPOFNCl.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.33,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ice Age",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100060,
            "tmdbId": "9806",
            "title": "The Incredibles",
            "releaseDate": "2004-11-05",
            "posterPath": "/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.04,
            "location": "\\\\DELL_E6540\\k_cartoons\\Incredibles",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100061,
            "tmdbId": "260513",
            "title": "Incredibles 2",
            "releaseDate": "2018-06-14",
            "posterPath": "/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.33,
            "location": "\\\\DELL_E6540\\k_cartoons\\Incredibles",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100062,
            "tmdbId": "150540",
            "title": "Inside Out",
            "releaseDate": "2015-06-09",
            "posterPath": "/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.48,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100063,
            "tmdbId": "9325",
            "title": "The Jungle Book",
            "releaseDate": "1967-10-18",
            "posterPath": "/xzpNa3RjKHfIijeqVuL72IgBvwy.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.95,
            "location": "\\\\DELL_E6540\\k_cartoons\\Jungle Book",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100064,
            "tmdbId": "14873",
            "title": "The Jungle Book 2",
            "releaseDate": "2003-02-07",
            "posterPath": "/DhuskQc9lSjPiYKr9hy0AZ7uiC.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 2.3,
            "location": "\\\\DELL_E6540\\k_cartoons\\Jungle Book",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100065,
            "tmdbId": "278927",
            "title": "The Jungle Book",
            "releaseDate": "2016-04-07",
            "posterPath": "/tOEOlmLP71IojeJ91dyJ9Nsb8O8.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 16.53,
            "location": "\\\\DELL_E6540\\k_cartoons\\Jungle Book",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100066,
            "tmdbId": "508965",
            "title": "Klaus",
            "releaseDate": "2019-11-08",
            "posterPath": "/q125RHUDgR4gjwh1QkfYuJLYkL.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 3.18,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100067,
            "tmdbId": "9502",
            "title": "Kung Fu Panda",
            "releaseDate": "2008-06-04",
            "posterPath": "/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.36,
            "location": "\\\\DELL_E6540\\k_cartoons\\Kung Fu Panda",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100068,
            "tmdbId": "49444",
            "title": "Kung Fu Panda 2",
            "releaseDate": "2011-05-25",
            "posterPath": "/mtqqD00vB4PGRt20gWtGqFhrkd0.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.81,
            "location": "\\\\DELL_E6540\\k_cartoons\\Kung Fu Panda",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100069,
            "tmdbId": "140300",
            "title": "Kung Fu Panda 3",
            "releaseDate": "2016-01-23",
            "posterPath": "/nlr2oxuYsHXt0wdtmzaOuVBoNC0.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.95,
            "location": "\\\\DELL_E6540\\k_cartoons\\Kung Fu Panda",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100070,
            "tmdbId": "15854",
            "title": "Kung Fu Panda: Secrets of the Furious Five",
            "releaseDate": "2008-11-08",
            "posterPath": "/tv52mGWtf13T3XEQj3Heow1whuc.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 1.15,
            "location": "\\\\DELL_E6540\\k_cartoons\\Kung Fu Panda\\Shorts",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100071,
            "tmdbId": "10340",
            "title": "Lady and the Tramp",
            "releaseDate": "1955-06-22",
            "posterPath": "/wXKeGea4htM7Yz3yo7hYXbs3FhV.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 17.54,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100072,
            "tmdbId": "8587",
            "title": "The Lion King",
            "releaseDate": "1994-06-23",
            "posterPath": "/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.24,
            "location": "\\\\DELL_E6540\\k_cartoons\\Lion King",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100073,
            "tmdbId": "9732",
            "title": "The Lion King II: Simba's Pride",
            "releaseDate": "1998-10-24",
            "posterPath": "/sWR1x6UCMCGN9xEf8RGhPS934X0.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.93,
            "location": "\\\\DELL_E6540\\k_cartoons\\Lion King",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100074,
            "tmdbId": "420818",
            "title": "The Lion King",
            "releaseDate": "2019-07-12",
            "posterPath": "/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 11.98,
            "location": "\\\\DELL_E6540\\k_cartoons\\Lion King",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100075,
            "tmdbId": "953",
            "title": "Madagascar",
            "releaseDate": "2005-05-25",
            "posterPath": "/uHkmbxb70IQhV4q94MiBe9dqVqv.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.8,
            "location": "\\\\DELL_E6540\\k_cartoons\\Madagascar",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100076,
            "tmdbId": "10527",
            "title": "Madagascar: Escape 2 Africa",
            "releaseDate": "2008-10-30",
            "posterPath": "/agRbLOHgN46TQO4YdKR462iR7To.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.82,
            "location": "\\\\DELL_E6540\\k_cartoons\\Madagascar",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100077,
            "tmdbId": "80321",
            "title": "Madagascar 3: Europe's Most Wanted",
            "releaseDate": "2012-06-06",
            "posterPath": "/ekraj4ksvIKeuvQVEevEJkuybZd.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.25,
            "location": "\\\\DELL_E6540\\k_cartoons\\Madagascar",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100078,
            "tmdbId": "270946",
            "title": "Penguins of Madagascar",
            "releaseDate": "2014-11-22",
            "posterPath": "/gbtwoYMWlG0HZe7sDaTOoijtXCu.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.4,
            "location": "\\\\DELL_E6540\\k_cartoons\\Madagascar",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100079,
            "tmdbId": "50321",
            "title": "Mars Needs Moms",
            "releaseDate": "2011-03-09",
            "posterPath": "/lOKqLd0ud1wdwaPK5h6bGNZIVLT.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.67,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100080,
            "tmdbId": "1267",
            "title": "Meet the Robinsons",
            "releaseDate": "2007-03-23",
            "posterPath": "/swsjj0jZtsx53Yp9zBORPwsmGWj.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.37,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100081,
            "tmdbId": "38055",
            "title": "Megamind",
            "releaseDate": "2010-10-28",
            "posterPath": "/uZ9ytt3sPTx62XTfN56ILSuYWRe.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 6.62,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100082,
            "tmdbId": "475215",
            "title": "Mirai",
            "releaseDate": "2018-06-16",
            "posterPath": "/b9XvI4Nehzi0nXyNVD6DtT39P6l.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.35,
            "location": "\\\\DELL_E6540\\k_cartoons\\Mirai (2018) [1080p]",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100083,
            "tmdbId": "277834",
            "title": "Moana",
            "releaseDate": "2016-11-23",
            "posterPath": "/vNJFiwtsl7Twww7C0uM4qPnygNw.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.8,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100084,
            "tmdbId": "585",
            "title": "Monsters, Inc.",
            "releaseDate": "2001-11-01",
            "posterPath": "/sgheSKxZkttIe8ONsf2sWXPgip3.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.62,
            "location": "\\\\DELL_E6540\\k_cartoons\\Monsters Inc",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100085,
            "tmdbId": "62211",
            "title": "Monsters University",
            "releaseDate": "2013-06-19",
            "posterPath": "/4rLfeHGIyDEQsqR22iajGSLFNME.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 6.5,
            "location": "\\\\DELL_E6540\\k_cartoons\\Monsters Inc",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100086,
            "tmdbId": "15512",
            "title": "Monsters vs Aliens",
            "releaseDate": "2009-03-19",
            "posterPath": "/aao1lKR87XFasISD3rr6UzkZyJ0.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.85,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100087,
            "tmdbId": "82703",
            "title": "Mr. Peabody & Sherman",
            "releaseDate": "2014-02-07",
            "posterPath": "/zfM3kcF6IiHkM84JsMFYAnKnEuh.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.37,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100088,
            "tmdbId": "10674",
            "title": "Mulan",
            "releaseDate": "1998-06-18",
            "posterPath": "/bJ0DxWQDLdjSJmFHwtximVdgJ5P.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.89,
            "location": "\\\\DELL_E6540\\k_cartoons\\Mulan",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100089,
            "tmdbId": "12242",
            "title": "Mulan II",
            "releaseDate": "2004-11-03",
            "posterPath": "/8cUIHYXpDFYX6r5ZviQuRKCVLJ2.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.64,
            "location": "\\\\DELL_E6540\\k_cartoons\\Mulan",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100090,
            "tmdbId": "8392",
            "title": "My Neighbor Totoro",
            "releaseDate": "1988-04-16",
            "posterPath": "/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.91,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100091,
            "tmdbId": "12",
            "title": "Finding Nemo",
            "releaseDate": "2003-05-30",
            "posterPath": "/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.85,
            "location": "\\\\DELL_E6540\\k_cartoons\\Nemo",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100092,
            "tmdbId": "127380",
            "title": "Finding Dory",
            "releaseDate": "2016-06-16",
            "posterPath": "/3UVe8NL1E2ZdUZ9EDlKGJY5UzE.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.81,
            "location": "\\\\DELL_E6540\\k_cartoons\\Nemo",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100093,
            "tmdbId": "12230",
            "title": "One Hundred and One Dalmatians",
            "releaseDate": "1961-01-25",
            "posterPath": "/9klDisS1sVb5LljRhpYJ0TUbPzt.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.45,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100094,
            "tmdbId": "508439",
            "title": "Onward",
            "releaseDate": "2020-02-29",
            "posterPath": "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.8,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100095,
            "tmdbId": "7484",
            "title": "Open Season",
            "releaseDate": "2006-09-29",
            "posterPath": "/w5Lctmkc1yah215Luxmci4djaiW.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100096,
            "tmdbId": "116149",
            "title": "Paddington",
            "releaseDate": "2014-11-24",
            "posterPath": "/hy70yIiMQEHMzRaVlMkOPlao2Ws.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.92,
            "location": "\\\\DELL_E6540\\k_cartoons\\Paddington",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100097,
            "tmdbId": "346648",
            "title": "Paddington 2",
            "releaseDate": "2017-11-09",
            "posterPath": "/zuXMvSQq9F7H29qzuUm0qyUqw6m.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.94,
            "location": "\\\\DELL_E6540\\k_cartoons\\Paddington",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100098,
            "tmdbId": "10693",
            "title": "Peter Pan",
            "releaseDate": "1953-02-05",
            "posterPath": "/6UTZmeQcxbtW32MyR5nKIx7ID4f.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.28,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100099,
            "tmdbId": "381719",
            "title": "Peter Rabbit",
            "releaseDate": "2018-02-07",
            "posterPath": "/lugOvdaNpbVGQK9TyMRDiUbLtY6.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.7,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100100,
            "tmdbId": "10895",
            "title": "Pinocchio",
            "releaseDate": "1940-02-23",
            "posterPath": "/1nCzeRj75ygXIG8r63TbkfeqM9x.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.76,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100101,
            "tmdbId": "16866",
            "title": "Planet 51",
            "releaseDate": "2009-11-19",
            "posterPath": "/x7Itcg3ZdExKwdKguy73WPEqosW.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.84,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100102,
            "tmdbId": "10530",
            "title": "Pocahontas",
            "releaseDate": "1995-06-14",
            "posterPath": "/kZ1ft0QZ4e3zDUPMBftEkwI9ftd.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.82,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100103,
            "tmdbId": "12429",
            "title": "Ponyo",
            "releaseDate": "2008-07-19",
            "posterPath": "/yp8vEZflGynlEylxEesbYasc06i.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 6.01,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100104,
            "tmdbId": "404368",
            "title": "Ralph Breaks the Internet",
            "releaseDate": "2018-11-20",
            "posterPath": "/qEnH5meR381iMpmCumAIMswcQw2.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.15,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ralph",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100105,
            "tmdbId": "82690",
            "title": "Wreck-It Ralph",
            "releaseDate": "2012-11-01",
            "posterPath": "/nsUAgWCxqbTD9wkKrv3nBGH2DVk.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.75,
            "location": "\\\\DELL_E6540\\k_cartoons\\Ralph",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100106,
            "tmdbId": "44896",
            "title": "Rango",
            "releaseDate": "2011-03-02",
            "posterPath": "/m5kz9dXHhAqzxknwuACvcgJmQSH.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 7.06,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100107,
            "tmdbId": "2062",
            "title": "Ratatouille",
            "releaseDate": "2007-06-22",
            "posterPath": "/npHNjldbeTHdKKw28bJKs7lzqzj.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.83,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100108,
            "tmdbId": "46195",
            "title": "Rio",
            "releaseDate": "2011-04-03",
            "posterPath": "/i8QoA3gOrvhU7sfihVVneNqlBuS.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.79,
            "location": "\\\\DELL_E6540\\k_cartoons\\Rio",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100109,
            "tmdbId": "172385",
            "title": "Rio 2",
            "releaseDate": "2014-03-19",
            "posterPath": "/tpCqpv8y0cDb7mgIPeTv70W9vmF.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.7,
            "location": "\\\\DELL_E6540\\k_cartoons\\Rio",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100110,
            "tmdbId": "11886",
            "title": "Robin Hood",
            "releaseDate": "1973-11-08",
            "posterPath": "/x9AvkYek0bGdxQSZ8W3lAjGrREm.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.07,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100111,
            "tmdbId": "9928",
            "title": "Robots",
            "releaseDate": "2005-03-10",
            "posterPath": "/fnKCh67l2DDG9NxxIlk9IpsXQ99.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.84,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100112,
            "tmdbId": "328111",
            "title": "The Secret Life of Pets",
            "releaseDate": "2016-06-18",
            "posterPath": "/gJo9G56QlXKRe2tcdDVSt28xVsP.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.94,
            "location": "\\\\DELL_E6540\\k_cartoons\\Secret Life of Pets",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100113,
            "tmdbId": "412117",
            "title": "The Secret Life of Pets 2",
            "releaseDate": "2019-05-24",
            "posterPath": "/q3mKnSkzp1doIsCye6ap4KIUAbu.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.54,
            "location": "\\\\DELL_E6540\\k_cartoons\\Secret Life of Pets",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100114,
            "tmdbId": "808",
            "title": "Shrek",
            "releaseDate": "2001-05-18",
            "posterPath": "/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.21,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100115,
            "tmdbId": "809",
            "title": "Shrek 2",
            "releaseDate": "2004-05-19",
            "posterPath": "/oljiDFPyMY437BRRV69AzVDSiKy.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.2,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100116,
            "tmdbId": "810",
            "title": "Shrek the Third",
            "releaseDate": "2007-05-17",
            "posterPath": "/jaNe16gE9zdAYyVwRqmlmRKshHm.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.19,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100117,
            "tmdbId": "10192",
            "title": "Shrek Forever After",
            "releaseDate": "2010-05-16",
            "posterPath": "/6HrfPZtKcGmX2tUWW3cnciZTaSD.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.86,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100118,
            "tmdbId": "417859",
            "title": "Puss in Boots",
            "releaseDate": "2011-10-28",
            "posterPath": "/eufJ36oQCauDc427ewaEvQrhZ6i.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.89,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100119,
            "tmdbId": "83201",
            "title": "Puss in Boots: The Three Diablos",
            "releaseDate": "2012-02-07",
            "posterPath": "/ptvbHUWpU8Nh6vrmSvjx4ESDgfC.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 1.22,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek\\Shorts",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100120,
            "tmdbId": "48466",
            "title": "Scared Shrekless",
            "releaseDate": "2010-10-28",
            "posterPath": "/iSl2JglSsOl0qUkqlmfor9h6U23.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 1.75,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek\\Shorts",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100121,
            "tmdbId": "25523",
            "title": "The Ghost of Lord Farquaad",
            "releaseDate": "2003-05-23",
            "posterPath": "/6yyGjJ0Og9LrM9XQ35quIhZpZiQ.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 0.94,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek\\Shorts",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100122,
            "tmdbId": "13394",
            "title": "Shrek the Halls",
            "releaseDate": "2007-11-28",
            "posterPath": "/kyCzpKpuF32nRl1QQgXqcQnnLAj.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 2.23,
            "location": "\\\\DELL_E6540\\k_cartoons\\Shrek\\Shorts",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100123,
            "tmdbId": "14411",
            "title": "Sinbad: Legend of the Seven Seas",
            "releaseDate": "2003-07-02",
            "posterPath": "/CQ1bthSN2uXDxovHUwH8mIB9zy.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 1.36,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100124,
            "tmdbId": "10882",
            "title": "Sleeping Beauty",
            "releaseDate": "1959-02-17",
            "posterPath": "/oQTDuu9kKLUXwb6XmBoqyAiVLhB.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.37,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100125,
            "tmdbId": "41513",
            "title": "The Smurfs",
            "releaseDate": "2011-07-29",
            "posterPath": "/vRhnslP2gW0QDym7BsMeSuioUfK.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.16,
            "location": "\\\\DELL_E6540\\k_cartoons\\Smurfs",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100126,
            "tmdbId": "77931",
            "title": "The Smurfs 2",
            "releaseDate": "2013-07-30",
            "posterPath": "/4zu8hbjp7bedcbetQssylLhpguk.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.94,
            "location": "\\\\DELL_E6540\\k_cartoons\\Smurfs",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100127,
            "tmdbId": "408",
            "title": "Snow White and the Seven Dwarfs",
            "releaseDate": "1937-12-21",
            "posterPath": "/4UvFMz8Ys0TaTTxma5e2tKj8u61.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.06,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 60
        },
        {
            "id": 100128,
            "tmdbId": "2300",
            "title": "Space Jam",
            "releaseDate": "1996-11-15",
            "posterPath": "/6h3FIr5CQFCBV8Xrv7XZLZbIQR0.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 6.43,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100129,
            "tmdbId": "431693",
            "title": "Spies in Disguise",
            "releaseDate": "2019-12-04",
            "posterPath": "/30YacPAcxpNemhhwX0PVUl9pVA3.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.67,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100130,
            "tmdbId": "129",
            "title": "Spirited Away",
            "releaseDate": "2001-07-20",
            "posterPath": "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.53,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100131,
            "tmdbId": "332210",
            "title": "Storks",
            "releaseDate": "2016-09-22",
            "posterPath": "/e33TYTXL8cIuS8j1oT079zLhUGw.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.68,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100132,
            "tmdbId": "9408",
            "title": "Surf's Up",
            "releaseDate": "2007-06-08",
            "posterPath": "/tTDsCVlDA8QR4Dc6t6nERfwl5z.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.63,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100133,
            "tmdbId": "38757",
            "title": "Tangled",
            "releaseDate": "2010-11-24",
            "posterPath": "/ym7Kst6a4uodryxqbGOxmewF235.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.32,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100134,
            "tmdbId": "37135",
            "title": "Tarzan",
            "releaseDate": "1999-06-18",
            "posterPath": "/a0Syo09bmNJgehjfeVL6meR9Mjh.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.94,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100135,
            "tmdbId": "481084",
            "title": "The Addams Family",
            "releaseDate": "2019-10-10",
            "posterPath": "/q1epO0eO8DWu8Vo8tPfvVlzW48T.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.48,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100136,
            "tmdbId": "10957",
            "title": "The Black Cauldron",
            "releaseDate": "1985-07-24",
            "posterPath": "/h64i9e6oJs2jrDZ4QzspXMqZhPF.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.07,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100137,
            "tmdbId": "228326",
            "title": "The Book of Life",
            "releaseDate": "2014-10-01",
            "posterPath": "/puTDvsUADxCA5NjJuwgEWqQ3xGA.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.13,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100138,
            "tmdbId": "170687",
            "title": "The Boxtrolls",
            "releaseDate": "2014-09-10",
            "posterPath": "/npBf0yc5Gt7aAyyVOcYtFyT2IPa.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 11.23,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100139,
            "tmdbId": "15370",
            "title": "The Cat Returns",
            "releaseDate": "2002-07-19",
            "posterPath": "/avPMO5cnaGHgLaNiAIhy33WoQLm.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.99,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100140,
            "tmdbId": "49519",
            "title": "The Croods",
            "releaseDate": "2013-03-20",
            "posterPath": "/27zvjVOtOi5ped1HSlJKNsKXkFH.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.77,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100141,
            "tmdbId": "378236",
            "title": "The Emoji Movie",
            "releaseDate": "2017-07-23",
            "posterPath": "/f5pF4OYzh4wb1dYL2ARQNdqUsEZ.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 9.77,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100142,
            "tmdbId": "11688",
            "title": "The Emperor's New Groove",
            "releaseDate": "2000-12-15",
            "posterPath": "/wwbgkXQBEKtnyIJapk6gUgWkVw8.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.37,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100143,
            "tmdbId": "10948",
            "title": "The Fox and the Hound",
            "releaseDate": "1981-07-10",
            "posterPath": "/1382VHxqZDXu2t8i46zf4fP71JG.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.42,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100144,
            "tmdbId": "105864",
            "title": "The Good Dinosaur",
            "releaseDate": "2015-11-14",
            "posterPath": "/dM50iVbcnzQUIoc9TmUUk0SP4P4.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.33,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100145,
            "tmdbId": "10545",
            "title": "The Hunchback of Notre Dame",
            "releaseDate": "1996-06-21",
            "posterPath": "/7k0fr2xLCTChjN8MnGNThTP9uEB.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.65,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100146,
            "tmdbId": "10144",
            "title": "The Little Mermaid",
            "releaseDate": "1989-11-17",
            "posterPath": "/plcZXvI310FkbwIptvd6rqk63LP.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 5.15,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100147,
            "tmdbId": "309809",
            "title": "The Little Prince",
            "releaseDate": "2015-07-29",
            "posterPath": "/je5Z7gbFTzrs3FPHINo9yGiHoVo.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.69,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100148,
            "tmdbId": "73723",
            "title": "The Lorax",
            "releaseDate": "2012-03-01",
            "posterPath": "/tePFnZFw5JvjwjQjaKkqDPNMLPU.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.71,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100149,
            "tmdbId": "9479",
            "title": "The Nightmare Before Christmas",
            "releaseDate": "1993-10-09",
            "posterPath": "/vFujAtlgTEh0ngIMs4hpGVdJ3TV.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100150,
            "tmdbId": "10198",
            "title": "The Princess and the Frog",
            "releaseDate": "2009-12-08",
            "posterPath": "/yprv5PbnEksoVj2v6XEnDBg9joR.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.89,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100151,
            "tmdbId": "509730",
            "title": "The Queen's Corgi",
            "releaseDate": "2019-02-13",
            "posterPath": "/xcl4vYTqqzwn3ihUpjCQz0jqhV3.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.9,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100152,
            "tmdbId": "10501",
            "title": "The Road to El Dorado",
            "releaseDate": "2000-03-31",
            "posterPath": "/ryXm7xp4aqQyda0FU2eMfHehPBg.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 5.11,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100153,
            "tmdbId": "9078",
            "title": "The Sword in the Stone",
            "releaseDate": "1963-12-25",
            "posterPath": "/7lyeeuhGAJSNXYEW34S8mJ1bwI8.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.06,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100154,
            "tmdbId": "10199",
            "title": "The Tale of Despereaux",
            "releaseDate": "2008-12-18",
            "posterPath": "/yADB4GsH2AvSHPsBVGjj8wByonk.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.65,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100155,
            "tmdbId": "202575",
            "title": "The House of Magic",
            "releaseDate": "2013-12-24",
            "posterPath": "/3R13g2XgblynIrQGF8geFZJPNvR.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.63,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100156,
            "tmdbId": "297270",
            "title": "Tinker Bell and the Legend of the NeverBeast",
            "releaseDate": "2014-12-12",
            "posterPath": "/3S0mmmpYStB3GqodRghcfOt81wQ.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.48,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100157,
            "tmdbId": "862",
            "title": "Toy Story",
            "releaseDate": "1995-10-30",
            "posterPath": "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.96,
            "location": "\\\\DELL_E6540\\k_cartoons\\Toy Story",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100158,
            "tmdbId": "863",
            "title": "Toy Story 2",
            "releaseDate": "1999-10-30",
            "posterPath": "/eVGu0zsezaSCuN67zgNhzjeNI9Z.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 6.84,
            "location": "\\\\DELL_E6540\\k_cartoons\\Toy Story",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100159,
            "tmdbId": "10193",
            "title": "Toy Story 3",
            "releaseDate": "2010-06-16",
            "posterPath": "/4cpGytCB0eqvRks4FAlJoUJiFPG.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 11.43,
            "location": "\\\\DELL_E6540\\k_cartoons\\Toy Story",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100160,
            "tmdbId": "301528",
            "title": "Toy Story 4",
            "releaseDate": "2019-06-19",
            "posterPath": "/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.47,
            "location": "\\\\DELL_E6540\\k_cartoons\\Toy Story",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100161,
            "tmdbId": "9016",
            "title": "Treasure Planet",
            "releaseDate": "2002-11-26",
            "posterPath": "/zMKatZ0c0NCoKzfizaCzVUcbKMf.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 10.25,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100162,
            "tmdbId": "136799",
            "title": "Trolls",
            "releaseDate": "2016-10-13",
            "posterPath": "/zKu5MNy9QW1a5ZHgv7iAp3kRZpE.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 8.15,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100163,
            "tmdbId": "14160",
            "title": "Up",
            "releaseDate": "2009-05-28",
            "posterPath": "/eAdO0qa9m0NFSVLZ26PvCwmPlsr.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.71,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100164,
            "tmdbId": "10681",
            "title": "WALL·E",
            "releaseDate": "2008-06-22",
            "posterPath": "/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 4.37,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100165,
            "tmdbId": "13691",
            "title": "Piglet's Big Movie",
            "releaseDate": "2003-03-16",
            "posterPath": "/9Dlb8HCzhO6rMv9KsOwrbL5P5kl.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 3.04,
            "location": "\\\\DELL_E6540\\k_cartoons\\Winnie the Pooh",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100166,
            "tmdbId": "13682",
            "title": "Pooh's Heffalump Movie",
            "releaseDate": "2005-02-11",
            "posterPath": "/e9yRYPCDIQV9npIOUUqeo1Thu4b.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 2.36,
            "location": "\\\\DELL_E6540\\k_cartoons\\Winnie the Pooh",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100167,
            "tmdbId": "250480",
            "title": "The Many Adventures of Winnie the Pooh",
            "releaseDate": "1977-03-11",
            "posterPath": "/2xwaFVLv5geVrFd81eUttv7OutF.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.11,
            "location": "\\\\DELL_E6540\\k_cartoons\\Winnie the Pooh",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100168,
            "tmdbId": "15655",
            "title": "The Tigger Movie",
            "releaseDate": "2000-02-11",
            "posterPath": "/lxuiGvLHIL1ZyePP7bn6FcKj0Mr.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 4.55,
            "location": "\\\\DELL_E6540\\k_cartoons\\Winnie the Pooh",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100169,
            "tmdbId": "51162",
            "title": "Winnie the Pooh",
            "releaseDate": "2011-04-13",
            "posterPath": "/wMZU69sPEP8dSNU0nMWVt7b54EQ.jpg",
            "type": "movie",
            "resolution": "HD",
            "size": 2.71,
            "location": "\\\\DELL_E6540\\k_cartoons\\Winnie the Pooh",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100170,
            "tmdbId": "400157",
            "title": "Wonder Park",
            "releaseDate": "2019-03-14",
            "posterPath": "/8KomINZhIuJeB4oB7k7tkq8tmE.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.23,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        },
        {
            "id": 100171,
            "tmdbId": "269149",
            "title": "Zootopia",
            "releaseDate": "2016-02-11",
            "posterPath": "/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg",
            "type": "movie",
            "resolution": "FullHD",
            "size": 7.56,
            "location": "\\\\DELL_E6540\\k_cartoons",
            "description": null,
            "frameRate": 24
        }
    ])
    return (
        <div className="Body">
            {movieList.map(m => <Card {...m}/>
            )}
        </div>
    );
};

export default body;